export const USER_REGISTER_REQUEST: String = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS: String = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL: String = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST: String = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS: String = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL: String = "USER_LOGIN_FAIL"

export const USER_LOGOUT_REQUEST: String = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS: String = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL: String = "USER_LOGOUT_FAIL"

//add, remove or update media from user
export const USER_MEDIA_ADD_REQUEST = "USER_MEDIA_ADD_REQUEST"
export const USER_MEDIA_ADD_SUCCESS = "USER_MEDIA_ADD_SUCCESS"
export const USER_MEDIA_ADD_FAIL = "USER_MEDIA_ADD_FAIL"

export const USER_MEDIA_REMOVE_REQUEST = "USER_MEDIA_REMOVE_REQUEST"
export const USER_MEDIA_REMOVE_SUCCESS = "USER_MEDIA_REMOVE_SUCCESS"
export const USER_MEDIA_REMOVE_FAIL = "USER_MEDIA_REMOVE_FAIL"

// ADD, REMOVE FROM ALREADY WATCHED
export const USER_ALREADY_WATCHED_ADD_REQUEST = "USER_ALREADY_WATCHED_ADD_REQUEST"
export const USER_ALREADY_WATCHED_ADD_SUCCESS = "USER_ALREADY_WATCHED_ADD_SUCCESS"
export const USER_ALREADY_WATCHED_ADD_FAIL = "USER_ALREADY_WATCHED_ADD_FAIL"

export const USER_ALREADY_WATCHED_REMOVE_REQUEST = "USER_ALREADY_WATCHED_REMOVE_REQUEST"
export const USER_ALREADY_WATCHED_REMOVE_SUCCESS = "USER_ALREADY_WATCHED_REMOVE_SUCCESS"
export const USER_ALREADY_WATCHED_REMOVE_FAIL = "USER_ALREADY_WATCHED_REMOVE_FAIL"

// ADD, REMOVE FROM EPISODES ALREADY WATCHED
export const USER_EPISODE_ALREADY_WATCHED_ADD_REQUEST = "USER_EPISODE_ALREADY_WATCHED_ADD_REQUEST"
export const USER_EPISODE_ALREADY_WATCHED_ADD_SUCCESS = "USER_EPISODE_ALREADY_WATCHED_ADD_SUCCESS"
export const USER_EPISODE_ALREADY_WATCHED_ADD_FAIL = "USER_EPISODE_ALREADY_WATCHED_ADD_FAIL"

export const USER_EPISODE_ALREADY_WATCHED_REMOVE_REQUEST = "USER_EPISODE_ALREADY_WATCHED_REMOVE_REQUEST"
export const USER_EPISODE_ALREADY_WATCHED_REMOVE_SUCCESS = "USER_EPISODE_ALREADY_WATCHED_REMOVE_SUCCESS"
export const USER_EPISODE_ALREADY_WATCHED_REMOVE_FAIL = "USER_EPISODE_ALREADY_WATCHED_REMOVE_FAIL"

// ADD, REMOVE FROM EPISODE BOOKMARKED
export const USER_ADD_EPISODE_BOOKMARK_REQUEST = "USER_ADD_EPISODE_BOOKMARK_REQUEST"
export const USER_ADD_EPISODE_BOOKMARK_SUCCESS = "USER_ADD_EPISODE_BOOKMARK_SUCCESS"
export const USER_ADD_EPISODE_BOOKMARK_FAIL = "USER_ADD_EPISODE_BOOKMARK_FAIL"

export const USER_REMOVE_EPISODE_BOOKMARK_REQUEST = "USER_REMOVE_EPISODE_BOOKMARK_REQUEST"
export const USER_REMOVE_EPISODE_BOOKMARK_SUCCESS = "USER_REMOVE_EPISODE_BOOKMARK_SUCCESS"
export const USER_REMOVE_EPISODE_BOOKMARK_FAIL = "USER_REMOVE_EPISODE_BOOKMARK_FAIL"

// UPDATE USER PROFILE IMAGE
export const UPDATE_USER_AVATAR_IMAGE_REQUEST = "UPDATE_USER_AVATAR_IMAGE_REQUEST"
export const UPDATE_USER_AVATAR_IMAGE_SUCCESS = "UPDATE_USER_AVATAR_IMAGE_SUCCESS"
export const UPDATE_USER_AVATAR_IMAGE_FAIL = "UPDATE_USER_AVATAR_IMAGE_FAIL"

// UPDATE USER PROFILE
export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST"
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS"
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL"

// DELETE ALL DATA FROM BOOKMARKS
export const DELETE_USER_MEDIA_REQUEST = "DELETE_USER_MEDIA_REQUEST"
export const DELETE_USER_MEDIA_SUCCESS = "DELETE_USER_MEDIA_SUCCESS"
export const DELETE_USER_MEDIA_FAIL = "DELETE_USER_MEDIA_FAIL"