export const USER_REGISTER_REQUEST: String =  "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS: String =  "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL: String =  "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST: String =  "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS: String =  "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL: String =  "USER_LOGIN_FAIL"

export const USER_LOGOUT_REQUEST: String =  "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS: String =  "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL: String =  "USER_LOGOUT_FAIL"