export const USER_REGISTER_REQUEST: String = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS: String = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL: String = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST: String = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS: String = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL: String = "USER_LOGIN_FAIL"

export const USER_LOGOUT_REQUEST: String = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS: String = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL: String = "USER_LOGOUT_FAIL"

//add, remove or update media from user
export const USER_MEDIA_ADD_REQUEST = "USER_MEDIA_ADD_REQUEST"
export const USER_MEDIA_ADD_SUCCESS = "USER_MEDIA_ADD_SUCCESS"
export const USER_MEDIA_ADD_FAIL = "USER_MEDIA_ADD_FAIL"

export const USER_MEDIA_REMOVE_REQUEST = "USER_MEDIA_REMOVE_REQUEST"
export const USER_MEDIA_REMOVE_SUCCESS = "USER_MEDIA_REMOVE_SUCCESS"
export const USER_MEDIA_REMOVE_FAIL = "USER_MEDIA_REMOVE_FAIL"

// export const USER_MEDIA_UPDATE_REQUEST = "USER_MEDIA_UPDATE_REQUEST"
// export const USER_MEDIA_UPDATE_SUCCESS = "USER_MEDIA_UPDATE_SUCCESS"
// export const USER_MEDIA_UPDATE_FAIL = "USER_MEDIA_UPDATE_FAIL"

