POST http://localhost:9000/users/register
Content-Type: application/json

{
    "name": "test01",
    "email":"email01@gmail",
    "password":"email01@gmail"
}

###

POST http://localhost:9000/users/login
Content-Type: application/json

{
    "email":"email",
    "password":"password"
}

###
PUT http://localhost:9000/users/change-adult-content-option
Content-Type: application/json

###
GET http://localhost:9000/users/bookmarked-media
Content-Type: application/json

{

}

###
GET http://localhost:9000/users/already-watched-media
Content-Type: application/json

{

}

###
POST http://localhost:9000/users/add-media
Content-Type: application/json


{
    "media": {
        "id": 1231232191,
        "fullTitle": "full name1",
        "nativeTitle": "native name1",
        "format": "tv",
        "type": "anime",
        "status": "Releasing",
        "isAdult": true,
        "fromGoGoAnime": false
    }
}

###

POST http://localhost:9000/users/remove-media
Content-Type: application/json

{
    "media": {
        "id": 1231232191
    }
}

###

PUT http://localhost:9000/users/update-user-profile
Content-Type: application/json

{
    "name": "Erick",
    "email": "",
    "currentPassword": "",
    "newPassword": ""
}

###
PUT http://localhost:9000/users/change-user-avatar-image
Content-Type: application/json

{
    "newAvatarImg": "nova url"
}

###
PUT http://localhost:9000/users/erase-media-added-data
Content-Type: application/json

{
}

###

POST http://localhost:9000/users/add-already-watched
Content-Type: application/json

